db:
    build: $PWD/mysql
    environment:
        MYSQL_DATABASE: wordpress
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - /Users/vmeron/docker/volumes/mysql:/var/lib/mysql
    ports:
        - "3306:3306"

php:
    image: splitbrain/phpfarm
    volumes:
        - /Users/vmeron/www/magento2:/var/www
    links:
        - db
    ports:
        - "80:8056"
#http:
#    image: httpd
#    volumes:
#        - /Users/vmeron/docker/volumes/apache:/usr/local/apache2/htdocs
#    ports:
#        - "80:80"
