db:
    build: $PWD/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - /Users/vmeron/docker/volumes/mysql:/var/lib/mysql
    ports:
        - "3306:3306"

php:
    extends:
        file: ../docker-compose.local.yml
        service: php
    build: $PWD/phpfarm
    environment:
        PHP_VERSION: 5.6.2
    volumes:
        - $PWD/../volumes/www:/var/www/drupal7/sites
    links:
        - db
    ports:
        - "80:80"
#http:
#    image: httpd
#    volumes:
#        - /Users/vmeron/docker/volumes/apache:/usr/local/apache2/htdocs
#    ports:
#        - "80:80"
